In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [60]:
df = pd.read_csv("../data/2022.csv")
df

,Program,University,COLOMBO,GAMPAHA,KALUTARA,MATALE,KANDY,NUWARA ELIYA,GALLE,MATARA,...,BATTICALOA,AMPARA,PUTTALAM,KURUNEGALA,ANURADHAPURA,POLONNARUWA,BADULLA,MONARAGALA,KEGALLE,RATNAPURA
0,MEDICINE,University of Colombo,2.4516,2.4412,2.4446,2.4981,2.5501,NQC,2.4478,2.4552,...,2.4902,2.4374,2.4946,2.445,2.5446,2.4695,2.5455,NQC,2.4552,2.4542
1,MEDICINE,University of Peradeniya,2.2279,2.2147,2.2204,2.215,2.2216,2.2598,2.2429,2.2225,...,2.2518,2.2384,2.2805,2.2114,2.2347,2.2591,2.2159,2.241,2.215,2.2112
2,MEDICINE,University of Sri Jayewardenepura,2.1465,2.1566,2.1474,2.1943,2.1512,NQC,2.1503,2.1557,...,2.1621,2.169,2.1698,2.1529,2.185,2.1774,2.1671,NQC,2.1465,2.1586
3,MEDICINE,University of Kelaniya,2.0526,2.0517,2.0514,2.0612,2.0545,2.0969,2.0791,2.0508,...,2.0571,2.0536,2.0552,2.0517,2.0651,2.1071,2.0619,2.1015,2.06,2.0526
4,MEDICINE,University of Jaffna,1.879,1.7278,1.784,1.7073,1.8169,1.7308,NQC,NQC,...,1.8226,1.8321,1.7175,1.8028,1.7109,1.7355,1.7099,1.7277,1.8226,1.752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,DANCE #,University of Jaffna,0.0655,-0.4526,-0.5592,0.4399,-0.0591,0.1365,NQC,NQC,...,0.4023,-0.2764,-0.4137,NQC,NQC,NQC,0.2607,NQC,0.9244,-0.1878
257,VISUAL & TECHNOLOGICAL ARTS #,Swami Vipulananda Institute of Aesthetic Studies,NQC,NQC,-0.4372,0.467,-0.0373,0.2056,NQC,-0.1418,...,0.6957,0.5714,0.2398,0.345,0.1912,-0.2883,0.1355,0.0474,-0.5133,0.1522
258,MUSIC #,Swami Vipulananda Institute of Aesthetic Studies,NQC,NQC,0.6484,-0.2345,-0.5822,0.5513,-0.9468,0.238,...,0.7486,0.0929,NQC,NQC,NQC,0.1868,-0.1891,NQC,0.5523,-0.0469
259,DANCE #,Swami Vipulananda Institute of Aesthetic Studies,0.2439,NQC,0.7635,-0.1395,-0.6296,0.0173,NQC,NQC,...,0.471,-0.1534,NQC,NQC,NQC,NQC,-0.2628,NQC,NQC,NQC
260,DRAMA & THEATRE #,Swami Vipulananda Institute of Aesthetic Studies,-0.3643,NQC,0.0772,0.4405,-0.1319,0.3666,NQC,NQC,...,0.9995,0.786,0.4275,0.0571,NQC,-0.9508,-0.0167,NQC,0.7294,0.4033

In [61]:
df.rename(columns=lambda x: x.title(), inplace=True)
df['Program'] = df['Program'].str.title()

In [62]:
df.columns[2:]

Index(['Colombo', 'Gampaha', 'Kalutara', 'Matale', 'Kandy', 'Nuwara Eliya',
       'Galle', 'Matara', 'Hambantota', 'Jaffna', 'Kilinochchi', 'Mannar',
       'Mullaitivu', 'Vavuniya', 'Trincomalee', 'Batticaloa', 'Ampara',
       'Puttalam', 'Kurunegala', 'Anuradhapura', 'Polonnaruwa', 'Badulla',
       'Monaragala', 'Kegalle', 'Ratnapura'],
      dtype='object')

In [63]:
for district in df.columns[2:]:
    df.loc[df[district] == "NQC", district] = 0.0
    df[district] = df[district].astype(float)

In [64]:
df

,Program,University,Colombo,Gampaha,Kalutara,Matale,Kandy,Nuwara Eliya,Galle,Matara,...,Batticaloa,Ampara,Puttalam,Kurunegala,Anuradhapura,Polonnaruwa,Badulla,Monaragala,Kegalle,Ratnapura
0,Medicine,University of Colombo,2.4516,2.4412,2.4446,2.4981,2.5501,0.0000,2.4478,2.4552,...,2.4902,2.4374,2.4946,2.4450,2.5446,2.4695,2.5455,0.0000,2.4552,2.4542
1,Medicine,University of Peradeniya,2.2279,2.2147,2.2204,2.2150,2.2216,2.2598,2.2429,2.2225,...,2.2518,2.2384,2.2805,2.2114,2.2347,2.2591,2.2159,2.2410,2.2150,2.2112
2,Medicine,University of Sri Jayewardenepura,2.1465,2.1566,2.1474,2.1943,2.1512,0.0000,2.1503,2.1557,...,2.1621,2.1690,2.1698,2.1529,2.1850,2.1774,2.1671,0.0000,2.1465,2.1586
3,Medicine,University of Kelaniya,2.0526,2.0517,2.0514,2.0612,2.0545,2.0969,2.0791,2.0508,...,2.0571,2.0536,2.0552,2.0517,2.0651,2.1071,2.0619,2.1015,2.0600,2.0526
4,Medicine,University of Jaffna,1.8790,1.7278,1.7840,1.7073,1.8169,1.7308,0.0000,0.0000,...,1.8226,1.8321,1.7175,1.8028,1.7109,1.7355,1.7099,1.7277,1.8226,1.7520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,Dance #,University of Jaffna,0.0655,-0.4526,-0.5592,0.4399,-0.0591,0.1365,0.0000,0.0000,...,0.4023,-0.2764,-0.4137,0.0000,0.0000,0.0000,0.2607,0.0000,0.9244,-0.1878
257,Visual & Technological Arts #,Swami Vipulananda Institute of Aesthetic Studies,0.0000,0.0000,-0.4372,0.4670,-0.0373,0.2056,0.0000,-0.1418,...,0.6957,0.5714,0.2398,0.3450,0.1912,-0.2883,0.1355,0.0474,-0.5133,0.1522
258,Music #,Swami Vipulananda Institute of Aesthetic Studies,0.0000,0.0000,0.6484,-0.2345,-0.5822,0.5513,-0.9468,0.2380,...,0.7486,0.0929,0.0000,0.0000,0.0000,0.1868,-0.1891,0.0000,0.5523,-0.0469
259,Dance #,Swami Vipulananda Institute of Aesthetic Studies,0.2439,0.0000,0.7635,-0.1395,-0.6296,0.0173,0.0000,0.0000,...,0.4710,-0.1534,0.0000,0.0000,0.0000,0.0000,-0.2628,0.0000,0.0000,0.0000
260,Drama & Theatre #,Swami Vipulananda Institute of Aesthetic Studies,-0.3643,0.0000,0.0772,0.4405,-0.1319,0.3666,0.0000,0.0000,...,0.9995,0.7860,0.4275,0.0571,0.0000,-0.9508,-0.0167,0.0000,0.7294,0.4033

In [65]:
df.to_csv('../data/2022_clean.csv', index=False)

print("DataFrame saved as CSV successfully.")

DataFrame saved as CSV successfully.

In [66]:
(df== 0.0).sum()

Program           0
University        0
Colombo           9
Gampaha          12
Kalutara         18
Matale           38
Kandy            10
Nuwara Eliya     42
Galle            28
Matara           38
Hambantota       32
Jaffna           52
Kilinochchi     109
Mannar           98
Mullaitivu      111
Vavuniya         80
Trincomalee      48
Batticaloa       39
Ampara           25
Puttalam         28
Kurunegala       18
Anuradhapura     28
Polonnaruwa      58
Badulla          19
Monaragala       44
Kegalle          23
Ratnapura         9
dtype: int64

In [67]:
df.max()

Program                 Yoga And Parapsychology
University      Wayamba University of Sri Lanka
Colombo                                  2.4516
Gampaha                                  2.4412
Kalutara                                 2.4446
Matale                                   2.4981
Kandy                                    2.5501
Nuwara Eliya                             2.2598
Galle                                    2.4478
Matara                                   2.4552
Hambantota                               2.4711
Jaffna                                   2.4504
Kilinochchi                              2.3267
Mannar                                   2.2964
Mullaitivu                               2.2786
Vavuniya                                 2.5134
Trincomalee                              2.4637
Batticaloa                               2.4902
Ampara                                   2.4374
Puttalam                                 2.8457
Kurunegala                                2.445
Anuradhapura                             2.5446
Polonnaruwa                              3.1166
Badulla                                  2.5455
Monaragala                               2.2985
Kegalle                                  2.4552
Ratnapura                                2.4542
dtype: object